version: "3"

services:
  nginx: 
    image: "nginx:stable-alpine"
    ports:
      - "${PORT_NGINX}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/php1
    depends_on:
      - php
      - mysql
  php:
    build:
      context: .
      dockerfile: "php.dockerfile"
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
    volumes:
      - ./src:/var/www/php1
  mysql:
    image: mysql:8.0
    ports:
      - "3316:3306"
    env_file:
      - env/mysql.env

  composer:
    build:
      context: .
      dockerfile: "composer.dockerfile"
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
    volumes:
      - ./src:/var/www/php1
    
  artisan:
    build:
      context: .
      dockerfile: "php.dockerfile"
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      UID: ${UID:-1000}
      GID: ${GID:-1000}
    volumes:
      - ./src:/var/www/php1
    entrypoint: ["php", "/var/www/php1/artisan"]